__title__ = "vfxClientToolkit"
__pretty_title__ = "VFX Client Toolkit"
__description__ = "Utilities for processing versions and notes for VFX client side."
__url__ = "https://github.com/debug/vfxClientToolkit"
__author__ = "Dom Drane"
__author_email__ = "dom@reality-debug.co.uk"
__license__ = "MIT"
__copyright__ = "Copyright 2020"
