name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        persist-credentials: true
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python3 setup.py install
        pip install sphinx_rtd_theme
    - name: Black reformatter check
      run: pipenv run black --check .
        #- name: mypy
        #  run: pipenv run mypy .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Build docs
      run: |
        pip install git+git://github.com/debug/vfxClientToolkit.git
        pip install PyGithub
        pip install GitPython
        pip install git+git://github.com/shotgunsoftware/python-api.git
        git checkout gh-pages
        export AUTHOR_MAIL=${{ secrets.AUTHOR_MAIL }}
        export ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
        export REPO_PATH=$PWD
        echo $AUTHOR_MAIL
        git remote remove origin
        git remote add origin https://debug:$ACCESS_TOKEN@github.com/debug/vfxClientToolkit.git
        cd docs
        pwd
        make html
        cd ../scripts
        git config user.name debug
        git config user.email AUTHOR_MAIL
        git add .
        python generate_docs
        git push --set-upstream origin gh-pages
